spring:
  thymeleaf:
    mode: html
    cache: false
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
#  mvc:
#    static-path-pattern: classpath:/static/**
#  resources:
#    static-locations: classpath:/static/,classpath:/public/
#  profiles:
#    active:
#    - dev
  data:
    mongodb:
      host: 149.129.255.119
      port: 27017
      database: diet
      username: admin
      password: admin
      
server:
  port: 443
  context-path: /
  ssl:
    key-store: classpath:1523975587641.pfx
    key-store-password: 1523975587641
    key-store-type: PKCS12
    
logging: 
  level:
    root: info 

#oss
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyid: LTAIZQaEAP0eiTPf
    keysecret: cbCCWzVIfZTtT1PuVd8X4JndUa36GZ
    bucketname: morgan-zmn
    filehost: diet
    


